'use client';

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  Sparkles,
  Wrench,
  AlertTriangle,
  Clock,
  CheckCircle2,
  Circle,
  Copy,
  RotateCw,
  Cpu,
  ShieldAlert,
  ListOrdered,
  Layers,
  ChevronDown,
  ChevronUp,
  SlidersHorizontal,
  Bot,
  Table as TableIcon,
  LayoutList,
  ExternalLink,
  Info
} from 'lucide-react';
import { useToast } from './Toast.tsx';
import { TelemetryData } from '../types.ts';

export interface DiagnosticStep {
  stepNumber: number;
  actionTitle: string;
  instructions: string;
  expectedReading: string;
  toolRequired: string;
}

export interface RecommendedDiagnosticPathData {
  primaryDiagnosis: string;
  confidenceScore: number;
  complexityLevel: string;
  estimatedBenchTimeMinutes: number;
  technicianBriefing: string;
  diagnosticSteps: DiagnosticStep[];
  requiredTools: string[];
  riskPrecautions: string[];
  partsLikelyNeeded: string[];
}

interface RecommendedDiagnosticPathProps {
  repairNotes: string;
  deviceManufacturer: string;
  deviceModel: string;
  symptoms?: string[];
  telemetry?: TelemetryData;
  onApplyPathToNotes?: (formattedPath: string) => void;
}

export default function RecommendedDiagnosticPath({
  repairNotes,
  deviceManufacturer,
  deviceModel,
  symptoms = [],
  telemetry,
  onApplyPathToNotes
}: RecommendedDiagnosticPathProps) {
  const { showToast } = useToast();
  const [loading, setLoading] = useState(false);
  const [pathData, setPathData] = useState<RecommendedDiagnosticPathData | null>(null);
  const [completedSteps, setCompletedSteps] = useState<number[]>([]);
  const [expandedStep, setExpandedStep] = useState<number | null>(1);
  const [viewMode, setViewMode] = useState<'table' | 'cards'>('table');
  const [autoGeneratedForNotes, setAutoGeneratedForNotes] = useState<string>('');

  const generateDiagnosticPath = async () => {
    if (!repairNotes.trim() && symptoms.length === 0) {
      showToast('Please enter repair notes or select symptoms to generate a diagnostic path.', 'error');
      return;
    }

    setLoading(true);
    try {
      const response = await fetch('/api/ai/diagnostic-path', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          repairNotes,
          deviceManufacturer,
          deviceModel,
          symptoms,
          telemetry
        })
      });

      const contentType = response.headers.get('content-type') || '';
      if (!contentType.includes('application/json')) {
        throw new Error(`Server returned non-JSON response (${response.status})`);
      }

      const res = await response.json();
      if (response.ok && res.success && res.path) {
        setPathData(res.path);
        setCompletedSteps([]);
        setExpandedStep(1);
        setAutoGeneratedForNotes(repairNotes);
        showToast('OpenAI Recommended Diagnostic Path generated!', 'success');
      } else {
        showToast(res.error || 'Failed to generate diagnostic path.', 'error');
      }
    } catch (err) {
      console.error('Error generating diagnostic path:', err);
      showToast('Connection error. Could not generate diagnostic path.', 'error');
    } finally {
      setLoading(false);
    }
  };

  // Auto-generate if notes exist and no path has been generated yet
  useEffect(() => {
    if (
      repairNotes.trim().length > 10 &&
      !pathData &&
      !loading &&
      autoGeneratedForNotes !== repairNotes
    ) {
      const timer = setTimeout(() => {
        generateDiagnosticPath();
      }, 1000);
      return () => clearTimeout(timer);
    }
  }, [repairNotes, deviceModel, symptoms]);

  const toggleStepCompleted = (stepNum: number) => {
    setCompletedSteps(prev =>
      prev.includes(stepNum) ? prev.filter(s => s !== stepNum) : [...prev, stepNum]
    );
  };

  const handleApplyToNotes = () => {
    if (!pathData) return;

    const formatted = `
=== OPENAI RECOMMENDED DIAGNOSTIC PATH ===
Primary Diagnosis: ${pathData.primaryDiagnosis} (${pathData.confidenceScore}% Confidence)
Complexity: ${pathData.complexityLevel} | Est. Bench Time: ${pathData.estimatedBenchTimeMinutes} mins

TECHNICIAN BRIEFING:
${pathData.technicianBriefing}

RECOMMENDED BENCH EXECUTION STEPS:
${pathData.diagnosticSteps.map(s => `${s.stepNumber}. [${s.actionTitle}] ${s.instructions} (Expected: ${s.expectedReading} | Tool: ${s.toolRequired})`).join('\n')}

REQUIRED BENCH TOOLS: ${pathData.requiredTools.join(', ')}
PARTS LIKELY NEEDED: ${pathData.partsLikelyNeeded.join(', ')}
SAFETY PRECAUTIONS: ${pathData.riskPrecautions.join('; ')}
`.trim();

    if (onApplyPathToNotes) {
      onApplyPathToNotes(formatted);
    } else {
      navigator.clipboard.writeText(formatted);
      showToast('Diagnostic Path copied to clipboard!', 'success');
    }
  };

  return (
    <div className="w-full bg-slate-900 text-white rounded-3xl p-6 md:p-8 space-y-6 shadow-2xl border border-slate-800 relative overflow-hidden">
      {/* Top Header */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 border-b border-slate-800 pb-5">
        <div className="flex items-center gap-3.5">
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-blue-600 to-indigo-600 flex items-center justify-center shrink-0 shadow-lg shadow-blue-500/20">
            <Sparkles className="w-6 h-6 text-white animate-pulse" />
          </div>
          <div>
            <div className="flex items-center gap-2.5 flex-wrap">
              <h3 className="text-xl font-bold text-white tracking-tight">Recommended Diagnostic Path</h3>
              <span className="px-2.5 py-0.5 bg-blue-500/20 text-blue-400 text-[10px] font-mono font-bold rounded-full border border-blue-500/30">
                OPENAI GPT-4o
              </span>
            </div>
            <p className="text-xs text-slate-400 mt-0.5">
              Technical step-by-step roadmap synthesized from hardware telemetry, symptoms, and schematics
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2.5 flex-wrap">
          {pathData && (
            <div className="flex items-center bg-slate-950/80 p-1 rounded-xl border border-slate-800">
              <button
                type="button"
                onClick={() => setViewMode('table')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                  viewMode === 'table'
                    ? 'bg-blue-600 text-white shadow-sm'
                    : 'text-slate-400 hover:text-white'
                }`}
                title="Full-width bench table view"
              >
                <TableIcon className="w-3.5 h-3.5" />
                <span>Table View</span>
              </button>
              <button
                type="button"
                onClick={() => setViewMode('cards')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                  viewMode === 'cards'
                    ? 'bg-blue-600 text-white shadow-sm'
                    : 'text-slate-400 hover:text-white'
                }`}
                title="Card drawer view"
              >
                <LayoutList className="w-3.5 h-3.5" />
                <span>Cards</span>
              </button>
            </div>
          )}

          <button
            type="button"
            onClick={generateDiagnosticPath}
            disabled={loading}
            className="px-5 py-2.5 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white text-xs font-bold rounded-xl transition-all shadow-lg shadow-blue-600/30 flex items-center justify-center gap-2 disabled:opacity-50"
          >
            {loading ? (
              <>
                <RotateCw className="w-4 h-4 animate-spin" />
                <span>Analyzing Notes...</span>
              </>
            ) : (
              <>
                <Bot className="w-4 h-4" />
                <span>{pathData ? 'Re-Analyze Path' : 'Generate Diagnostic Path'}</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Main Content Area */}
      <AnimatePresence mode="wait">
        {loading ? (
          <motion.div
            key="loading"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="py-14 flex flex-col items-center justify-center text-center space-y-4"
          >
            <div className="relative">
              <div className="w-16 h-16 rounded-2xl bg-blue-600/20 border border-blue-500/30 flex items-center justify-center animate-bounce">
                <Cpu className="w-8 h-8 text-blue-400" />
              </div>
              <div className="absolute -top-1 -right-1 w-4 h-4 bg-emerald-500 rounded-full animate-ping" />
            </div>
            <div className="space-y-1">
              <p className="text-sm font-bold text-slate-200">Synthesizing Diagnostic Execution Plan...</p>
              <p className="text-xs text-slate-400">Evaluating repair notes against D&CP Lab schematics & power rail specs</p>
            </div>
          </motion.div>
        ) : pathData ? (
          <motion.div
            key="result"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            className="space-y-6 w-full"
          >
            {/* Summary Header Badge Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 w-full">
              <div className="sm:col-span-2 bg-slate-800/80 border border-slate-700/80 rounded-2xl p-4.5 space-y-2.5 shadow-sm">
                <span className="text-[10px] font-bold uppercase tracking-wider text-blue-400 flex items-center gap-1.5">
                  <Cpu className="w-3.5 h-3.5" />
                  Primary Suspected Fault
                </span>
                <p className="text-base font-bold text-white leading-snug">{pathData.primaryDiagnosis}</p>
                <div className="flex items-center gap-2.5 pt-1">
                  <div className="w-full bg-slate-700 h-2 rounded-full overflow-hidden">
                    <div
                      className="bg-emerald-400 h-full rounded-full transition-all duration-500"
                      style={{ width: `${pathData.confidenceScore}%` }}
                    />
                  </div>
                  <span className="text-xs font-mono font-bold text-emerald-400 shrink-0">
                    {pathData.confidenceScore}% Confidence
                  </span>
                </div>
              </div>

              <div className="bg-slate-800/80 border border-slate-700/80 rounded-2xl p-4.5 flex flex-col justify-between shadow-sm">
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 flex items-center gap-1.5">
                  <Layers className="w-3.5 h-3.5 text-amber-400" />
                  Service Complexity
                </span>
                <p className="text-base font-bold text-amber-300 mt-1">{pathData.complexityLevel}</p>
                <span className="text-[10px] text-slate-400 mt-2 font-mono">D&CP Standard Classification</span>
              </div>

              <div className="bg-slate-800/80 border border-slate-700/80 rounded-2xl p-4.5 flex flex-col justify-between shadow-sm">
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 flex items-center gap-1.5">
                  <Clock className="w-3.5 h-3.5 text-indigo-400" />
                  Est. Bench Time
                </span>
                <p className="text-base font-bold text-indigo-300 mt-1">{pathData.estimatedBenchTimeMinutes} Minutes</p>
                <span className="text-[10px] text-slate-400 mt-2 font-mono">Isolation & Testing Target</span>
              </div>
            </div>

            {/* Technician Briefing Box */}
            <div className="w-full bg-blue-950/40 border border-blue-500/30 rounded-2xl p-5 space-y-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-blue-300 flex items-center gap-2">
                <Bot className="w-4 h-4 text-blue-400" />
                Technician Triage Briefing
              </h4>
              <p className="text-xs md:text-sm text-slate-200 leading-relaxed font-normal">
                {pathData.technicianBriefing}
              </p>
            </div>

            {/* Diagnostic Path Container - Full Width */}
            <div className="space-y-3 w-full">
              <div className="flex items-center justify-between flex-wrap gap-2">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-300 flex items-center gap-2">
                  <ListOrdered className="w-4 h-4 text-blue-400" />
                  Sequential Diagnostic Bench Execution ({completedSteps.length}/{pathData.diagnosticSteps.length} Verified)
                </h4>
                {completedSteps.length === pathData.diagnosticSteps.length && (
                  <span className="text-xs font-bold text-emerald-400 bg-emerald-500/20 px-3 py-1 rounded-full border border-emerald-500/30 flex items-center gap-1.5">
                    <CheckCircle2 className="w-3.5 h-3.5" /> All Diagnostic Steps Verified
                  </span>
                )}
              </div>

              {/* TABLE VIEW: Generous, clear, full-width responsive matrix */}
              {viewMode === 'table' ? (
                <div className="w-full overflow-hidden rounded-2xl border border-slate-800 bg-slate-950/80 shadow-inner">
                  <div className="w-full min-w-[600px] overflow-x-auto">
                    <table className="w-full min-w-[600px] md:min-w-[760px] text-left border-collapse">
                      <thead>
                        <tr className="border-b border-slate-800 bg-slate-900/90 text-[11px] font-mono font-bold uppercase tracking-wider text-slate-400">
                          <th className="py-3.5 px-4 w-16 text-center">#</th>
                          <th className="py-3.5 px-4 w-48">Action / Test Point</th>
                          <th className="py-3.5 px-4 min-w-[240px]">Diagnostic Instructions & Procedure</th>
                          <th className="py-3.5 px-4 w-44">Expected Nominal</th>
                          <th className="py-3.5 px-4 w-40">Required Tool</th>
                          <th className="py-3.5 px-4 w-28 text-center">Status</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-slate-800/80 text-xs">
                        {pathData.diagnosticSteps.map((step) => {
                          const isDone = completedSteps.includes(step.stepNumber);
                          return (
                            <tr
                              key={step.stepNumber}
                              onClick={() => toggleStepCompleted(step.stepNumber)}
                              className={`cursor-pointer transition-colors ${
                                isDone
                                  ? 'bg-emerald-950/20 hover:bg-emerald-950/30'
                                  : 'hover:bg-slate-800/50 even:bg-slate-900/30'
                              }`}
                            >
                              {/* Step Number */}
                              <td className="py-4 px-4 text-center align-top">
                                <span className={`inline-flex items-center justify-center w-7 h-7 rounded-xl font-mono text-xs font-bold border ${
                                  isDone
                                    ? 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40'
                                    : 'bg-slate-800 text-blue-400 border-slate-700'
                                }`}>
                                  {step.stepNumber}
                                </span>
                              </td>

                              {/* Title / Action */}
                              <td className="py-4 px-4 align-top">
                                <span className={`font-bold block text-sm leading-snug ${isDone ? 'line-through text-slate-400' : 'text-white'}`}>
                                  {step.actionTitle}
                                </span>
                              </td>

                              {/* Procedure / Instructions */}
                              <td className="py-4 px-4 align-top">
                                <p className={`leading-relaxed ${isDone ? 'text-slate-400 line-through' : 'text-slate-300'}`}>
                                  {step.instructions}
                                </p>
                              </td>

                              {/* Expected Reading */}
                              <td className="py-4 px-4 align-top">
                                <div className="inline-block p-2 rounded-xl bg-emerald-950/30 border border-emerald-500/20 max-w-full">
                                  <span className="text-[10px] text-emerald-400/80 uppercase font-mono block font-bold">
                                    Target Value
                                  </span>
                                  <span className="font-mono font-bold text-emerald-300 text-xs break-words">
                                    {step.expectedReading}
                                  </span>
                                </div>
                              </td>

                              {/* Required Tool */}
                              <td className="py-4 px-4 align-top">
                                <div className="inline-block p-2 rounded-xl bg-blue-950/30 border border-blue-500/20 max-w-full">
                                  <span className="text-[10px] text-blue-400/80 uppercase font-mono block font-bold">
                                    Instrument
                                  </span>
                                  <span className="font-bold text-blue-300 text-xs break-words">
                                    {step.toolRequired}
                                  </span>
                                </div>
                              </td>

                              {/* Verification Checkbox */}
                              <td className="py-4 px-4 align-top text-center" onClick={(e) => e.stopPropagation()}>
                                <button
                                  type="button"
                                  onClick={() => toggleStepCompleted(step.stepNumber)}
                                  className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold transition-all border ${
                                    isDone
                                      ? 'bg-emerald-600 text-white border-emerald-500 shadow-sm'
                                      : 'bg-slate-800 text-slate-400 hover:text-white border-slate-700 hover:border-slate-600'
                                  }`}
                                >
                                  {isDone ? (
                                    <>
                                      <CheckCircle2 className="w-3.5 h-3.5" />
                                      <span>Done</span>
                                    </>
                                  ) : (
                                    <>
                                      <Circle className="w-3.5 h-3.5" />
                                      <span>Verify</span>
                                    </>
                                  )}
                                </button>
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  </div>
                </div>
              ) : (
                /* CARD VIEW: Expandable interactive drawer cards */
                <div className="space-y-3 w-full">
                  {pathData.diagnosticSteps.map((step) => {
                    const isDone = completedSteps.includes(step.stepNumber);
                    const isExpanded = expandedStep === step.stepNumber;

                    return (
                      <div
                        key={step.stepNumber}
                        className={`w-full border rounded-2xl transition-all overflow-hidden ${
                          isDone
                            ? 'bg-slate-800/40 border-emerald-500/30'
                            : isExpanded
                            ? 'bg-slate-800 border-blue-500/50 shadow-lg'
                            : 'bg-slate-800/70 border-slate-700/80 hover:border-slate-600'
                        }`}
                      >
                        <div
                          className="p-4 flex items-center justify-between gap-3 cursor-pointer select-none"
                          onClick={() => setExpandedStep(isExpanded ? null : step.stepNumber)}
                        >
                          <div className="flex items-center gap-3 min-w-0">
                            <button
                              type="button"
                              onClick={(e) => {
                                e.stopPropagation();
                                toggleStepCompleted(step.stepNumber);
                              }}
                              className="p-1 text-slate-400 hover:text-white transition-colors shrink-0"
                            >
                              {isDone ? (
                                <CheckCircle2 className="w-5 h-5 text-emerald-400" />
                              ) : (
                                <Circle className="w-5 h-5 text-slate-500" />
                              )}
                            </button>

                            <div className="min-w-0">
                              <div className="flex items-center gap-2 flex-wrap">
                                <span className="text-xs font-mono font-bold text-blue-400">
                                  STEP {step.stepNumber}
                                </span>
                                <h5 className={`text-sm font-bold truncate ${isDone ? 'line-through text-slate-400' : 'text-white'}`}>
                                  {step.actionTitle}
                                </h5>
                              </div>
                            </div>
                          </div>

                          <div className="flex items-center gap-2 shrink-0">
                            <span className="text-[10px] bg-slate-900/80 text-slate-300 px-2 py-1 rounded-lg border border-slate-700/60 font-mono hidden sm:inline-block">
                              {step.toolRequired}
                            </span>
                            {isExpanded ? (
                              <ChevronUp className="w-4 h-4 text-slate-400" />
                            ) : (
                              <ChevronDown className="w-4 h-4 text-slate-400" />
                            )}
                          </div>
                        </div>

                        {isExpanded && (
                          <div className="px-4 pb-4 pt-1 border-t border-slate-700/60 space-y-3 bg-slate-900/40">
                            <p className="text-xs md:text-sm text-slate-300 leading-relaxed">
                              {step.instructions}
                            </p>

                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-1 text-xs">
                              <div className="p-3 rounded-xl bg-slate-800/90 border border-slate-700/60">
                                <span className="text-[10px] font-bold text-slate-400 block uppercase tracking-wider">
                                  Expected Nominal Reading
                                </span>
                                <span className="font-mono font-bold text-emerald-300 text-sm mt-0.5 block">
                                  {step.expectedReading}
                                </span>
                              </div>

                              <div className="p-3 rounded-xl bg-slate-800/90 border border-slate-700/60">
                                <span className="text-[10px] font-bold text-slate-400 block uppercase tracking-wider">
                                  Required Instrument / Tool
                                </span>
                                <span className="font-bold text-blue-300 text-sm mt-0.5 block">
                                  {step.toolRequired}
                                </span>
                              </div>
                            </div>
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}
            </div>

            {/* Tools, Parts & Precautions Grid - Full Span */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 pt-2 w-full">
              {/* Tools */}
              <div className="bg-slate-800/60 border border-slate-700/60 rounded-2xl p-4.5 space-y-2.5">
                <span className="text-xs font-bold text-blue-400 uppercase tracking-wider flex items-center gap-1.5">
                  <Wrench className="w-3.5 h-3.5" />
                  Required Bench Tools
                </span>
                <div className="flex flex-wrap gap-1.5">
                  {pathData.requiredTools.map((tool, idx) => (
                    <span key={idx} className="px-2.5 py-1 bg-slate-900 text-slate-300 text-xs font-medium rounded-lg border border-slate-700/80">
                      {tool}
                    </span>
                  ))}
                </div>
              </div>

              {/* Likely Parts */}
              <div className="bg-slate-800/60 border border-slate-700/60 rounded-2xl p-4.5 space-y-2.5">
                <span className="text-xs font-bold text-indigo-400 uppercase tracking-wider flex items-center gap-1.5">
                  <SlidersHorizontal className="w-3.5 h-3.5" />
                  Likely Needed Parts
                </span>
                <div className="flex flex-wrap gap-1.5">
                  {pathData.partsLikelyNeeded.map((part, idx) => (
                    <span key={idx} className="px-2.5 py-1 bg-slate-900 text-slate-300 text-xs font-medium rounded-lg border border-slate-700/80">
                      {part}
                    </span>
                  ))}
                </div>
              </div>

              {/* Safety Precautions */}
              <div className="bg-amber-950/30 border border-amber-500/30 rounded-2xl p-4.5 space-y-2.5">
                <span className="text-xs font-bold text-amber-400 uppercase tracking-wider flex items-center gap-1.5">
                  <ShieldAlert className="w-3.5 h-3.5 text-amber-400" />
                  Hazard & Risk Precautions
                </span>
                <ul className="space-y-1.5 text-xs text-amber-200/90 list-disc list-inside">
                  {pathData.riskPrecautions.map((risk, idx) => (
                    <li key={idx} className="leading-snug">
                      {risk}
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Bottom Actions */}
            <div className="pt-3 flex flex-col sm:flex-row items-center justify-between gap-3 border-t border-slate-800">
              <p className="text-[11px] text-slate-400 flex items-center gap-1.5">
                <Info className="w-3.5 h-3.5 text-slate-500" />
                Spokane Technical Lab Roadmap &bull; Adheres to ESD S20.20 & IPC-A-610 Workmanship Standards.
              </p>

              <button
                type="button"
                onClick={handleApplyToNotes}
                className="w-full sm:w-auto px-5 py-2.5 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold rounded-xl transition-all shadow-md flex items-center justify-center gap-2"
              >
                <Copy className="w-4 h-4" />
                <span>Apply Path to Work Order Notes</span>
              </button>
            </div>
          </motion.div>
        ) : (
          <motion.div
            key="empty"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="py-12 text-center space-y-4 border-2 border-dashed border-slate-800 rounded-2xl p-6"
          >
            <div className="w-12 h-12 bg-slate-800 text-slate-400 rounded-2xl flex items-center justify-center mx-auto">
              <Bot className="w-6 h-6" />
            </div>
            <div className="max-w-md mx-auto space-y-1">
              <h4 className="text-sm font-bold text-white">No Diagnostic Path Generated Yet</h4>
              <p className="text-xs text-slate-400">
                Enter repair notes or symptom details above, then click <strong className="text-slate-200">Generate Diagnostic Path</strong> to generate step-by-step bench instructions.
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
